### ISSUE TITLE
Getting started with phpunit: documentation is unclear

### ISSUE THREAD

**Issue by jacalata** [sebastianbergmann/phpunit-documentation-english#125]
I'm following the docs at https://phpunit.readthedocs.io/en/8.0/writing-tests-for-phpunit.html, trying to write my first phpunit tests. I installed phpunit with composer and created a broken test, to validate. However the test won't run. Here's what I did: what am I missing?

$project-dir> composer --dev require phpunit
$project-dir> mkdir tests
$project-dir/tests>  // create test file TestTheTest.php
```
<?php
use PHPUnit\Framework\TestCase;
class TestTheTest extends TestCase
{
    public function testFailure()
    {
        $this->assertEmpty([]);
    }
}
?>
```
$project-dir/tests>phpunit TestTheTest.php
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in project-dir\tests\TestTheTest.php on line 3
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in project-dir\tests\TestTheTest.php on line 3

**Comment by sebastianbergmann** [comment]
You use `phpunit` instead of `./vendor/bin/phpunit` to invoke PHPUnit. `./vendor/bin/phpunit` is the executable installed by Composer in the `composer --dev require phpunit` step. `phpunit` is likely an outdated version of PHPUnit that you have on your `$PATH`. Use `which phpunit` to find it and then delete it.

**Comment by jacalata** [comment]
Great. I was hoping to find a way to improve the documentation, rather than just getting an answer here. Is this something that you're ok with adding?
