### ISSUE TITLE
Confusing/conflicting situation with CodeCoverageXX annotations

### ISSUE THREAD

**Issue by uuf6429** [sebastianbergmann/phpunit-documentation-english#383]
At the end of https://docs.phpunit.de/en/10.5/code-coverage.html#ignoring-code-blocks one sees the following (same message appears in v11):
> Please note that while annotations for test code have been deprecated and support for them will be removed in PHPUnit 12, the `@codeCoverageIgnore`, `@codeCoverageIgnoreStart`, and `@codeCoverageIgnoreEnd` annotations have not been deprecated and support for them will not be removed.

After reading that page I was left wondering why attributes weren't implemented for `@codeCoverageXX` annotations. A cursory web search led me to sebastianbergmann/phpunit#5235, which explained (to my surprise) that the attributes were implemented and then removed.

I don't get it, why weren't the annotations also deprecated when the attributes (which are superior in many ways) have been deprecated and removed? The main point behind removing the attributes seemed to be that production code would depend on tests - isn't that exactly the same with the annotations??

Further digging leads to sebastianbergmann/phpunit#5237 and sebastianbergmann/phpunit#5513 - whose implementation completely contradicts the earlier comments.

It's quite unfortunate how this well thought out change (I'm not being sarcastic), has been poorly presented to end users.

_I wasn't sure where this issue is best posted, but it feels mostly related to documentation._

----

On a related point, PhpStorm marks those annotations as deprecated and suggests replacing them with attributes, which then fails because the attributes are missing. 🙄 
That was already reported here: https://youtrack.jetbrains.com/issue/WI-78517/PHPUnit-annotation-inspection-suggests-CodeCoverageIgnore

----

PS: Apologies for the tone, without PHPUnit it would definitely be a worse Monday. 😊

**Comment by sebastianbergmann** [comment]
All annotations in code comments in test code are deprecated and support for them will be removed in PHPUnit 12.

The only annotations in code comments that are supported in production code are `@codeCoverageIgnore`, `@codeCoverageIgnoreStart`, and `@codeCoverageIgnoreEnd`. These are not deprecated and will not be removed. Why they cannot be replaced by attributes is discussed in https://github.com/sebastianbergmann/phpunit/issues/5235.

> Further digging leads to https://github.com/sebastianbergmann/phpunit/issues/5237 and https://github.com/sebastianbergmann/phpunit/issues/5513 - whose implementation completely contradicts the earlier comments.

I am sorry about the confusion. For a short period of time, this approach seemed to make sense. Unfortunately, it turned out to not solve the problem it was supposed to solve while also leading to more confusion.

> PhpStorm marks those annotations as deprecated and suggests replacing them with attributes

I am not the vendor of PhpStorm and there is nothing I can do about bugs in PhpStorm other than to report them. Which in this case, as you mention, has already been done.
